# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation
---
APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes
  - ACTION
  - GIT
  - JSON
  - CREDENTIALS
  - CSS
  - HTML
DISABLE_LINTERS:
  - ACTION_ACTIONLINT
  - DOCKERFILE_HADOLINT
  - MAKEFILE_CHECKMAKE
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_ISORT
  - PYTHON_MYPY
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY
  - YAML_PRETTIER
  - YAML_V8R
  - JAVASCRIPT_STANDARD
  - JAVASCRIPT_PRETTIER
  - MARKDOWN_MARKDOWN_LINK_CHECK
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
DOCKERFILE_DOCKERFILELINT_CONFIG_FILE: "LINTER_DEFAULT"
BASH_SHFMT_FILTER_REGEX_EXCLUDE: "(\\.devcontainer)"
JAVASCRIPT_ES_CONFIG_FILE: ".eslintrc.js"
JAVASCRIPT_ES_FILE_EXTENSIONS: [".js"]
JAVASCRIPT_ES_FILTER_REGEX_EXCLUDE: "(web_app_ui_mvp/plugins|web_app_ui/src|web_app_ui_react/src)"
